### ISSUE TITLE
npm install not adding all modules

### ISSUE THREAD

**Issue by weisinlakd** [nestjs/javascript-starter#40]
Hi, wanted to try the framework and the project does not run since its missing modules after `npm install`. I only cloned the repo and run both `npm install` and `npm run start`.

Error stack: 

```
babel-node index.js

internal/modules/cjs/loader.js:438
      throw e;
      ^

Error: Cannot find module 'C:\Users\Enzo\Desktop\hipercore-nest\node_modules\@babel\compat-data\data\corejs3-shipped-proposals'
    at createEsmNotFoundErr (internal/modules/cjs/loader.js:907:15)
    at finalizeEsmResolution (internal/modules/cjs/loader.js:900:15)
    at resolveExports (internal/modules/cjs/loader.js:432:14)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\Enzo\Desktop\hipercore-nest\node_modules\@babel\preset-env\lib\polyfills\corejs3\usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1063:30) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\Enzo\\Desktop\\hipercore-nest\\node_modules\\@babel\\compat-data\\package.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nest-babel-starter@1.0.0 start: `babel-node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nest-babel-starter@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
